version: '2'
services:
  db:
    image: postgres:9.5.4
    volumes:
      - ~/-docker-volumes/websocket_test/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'websocket_test'
      POSTGRES_PASSWORD: 'password'
  redis:
    image: redis:3.2.3
    ports:
      - '6379:6379'
    volumes:
      - ~/.docker-volumes/websocket_test/redis/data:/var/lib/redis/data
  websocket:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - "3002:3245"
    volumes:
      - .:/websocket_test
    env_file:
      - .websocket_test.env